const quotes = [
  {author: 'Edward Teller',
   text: 'The science of today is the technology of tomorrow.'},
  {author:'Ernest Hemingway',
   text:'But man is not made for defeat. A man can be destroyed but not defeated.'},
  {author:'Colin Powell',
   text:'Success is the result of perfection, hard work, learning from failure, loyalty, and persistence.'},
  {author:'Mark Twain',
   text:'Climate is what we expect, weather is what we get.'},
  {author:'George Carlin',
   text:'Weather forecast for tonight: dark. Continued dark overnight, with widely scattered light by morning. '},
  {author:'Wendell Berry',
   text:'The Earth is what we all have in common.'},
  {author:'George Bernard Shaw',
   text:'Progress is impossible without change, and those who cannot change their minds cannot change anything.'},
  {author:'Margaret Mead',
   text:'Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it is the only thing that ever has.'},
  {author:'Jimmy Carter',
   text:'Like music and art, love of nature is a common language that can transcend political or social boundaries.'},
  {author:'Antoine de Saint-Exupéry',
   text:'And now here is my secret, a very simple secret: It is only with the heart that one can see rightly; what is essential is invisible to the eye.'},
  {author:'Carl Sagan',
   text:' To me, it underscores our responsibility to deal more kindly with one another, and to preserve and cherish the pale blue dot, the only home we\'ve ever known.'},
  {author:'Albert Einstein',
   text:'If you can\'t explain it to a six year old, you don\'t understand it yourself.'},
  {author:'Albert Einstein',
   text:'A clever person solves a problem. A wise person avoids it.'},
  {author:'Henry Thoreau',
   text:'A sky without clouds is a meadow without flowers, a sea without sails. '},
  {author:'Henry Wadsworth Longfellow',
   text:'Every dew-drop and rain-drop had a whole heaven within it. '},
  {author:'Josh Billings',
   text:'Everything on this earth is bought and sold, except air and water, and they would be if a kind Creator had not made the supply too grate for the demand.'},
  {author:'Sir Jack Balwin',
   text:'The number of stars making up the Milky Way is about 10^11 or something like the number of raindrops falling in Hyde Park in a day\'s heavy rain. '},
  {author:'Jacques-Yves Cousteau',
   text:'The sea is the universal sewer where all kinds of pollution end up conveyed by rain from the atmosphere and from the mainland.'},
  {author:'Jan Ingenhousz',
   text:'It will, perhaps appear probable, that one of the great laboratories of nature for cleaning and purifying the air of our atmosphere is placed in the substance of the leaves, and put in action by the influence of the light. '},
  {author:'Norman John Berrill',
   text:'Life can be thought of as water kept at the right temperature in the right atmosphere in the right light for a long enough period of time. '}
]
